name: "Photons Interactor"
version: "0.12.0.3"
slug: "photons-interactor"
description: >-
  Photons Interactor provides a local RESTful API for LIFX devices
arch:
  - amd64
  - aarch64
  - armhf
  - armv7
  - i386
url: "https://photons.delfick.com/apps/interactor/homeassistant.html"
host_network: true
apparmor: false
hassio_api: true
init: false
options:
  enable_logging: false
schema:
  enable_logging: bool
ports:
  6100/tcp: 6100
ports_description:
  6100: Photons Interactor REST API
map:
  - config:rw
