---
build_from:
  aarch64: home-assistant/aarch64-base:3.16
  amd64: home-assistant/amd64-base:3.16
  armhf: home-assistant/armhf-base:3.16
  armv7: home-assistant/armv7-base:3.16
  i386: home-assistant/i386-base:3.16
codenotary:
  signer: me@dje.li
  base_image: notary@home-assistant.io
