image: "djelibeybi/hassio-flic-{arch}"
shadow_repository: "ghcr.io/djelibeybi"
build_from:
  aarch64: ghcr.io/home-assistant/aarch64-base-debian:bullseye
  amd64: ghcr.io/home-assistant/amd64-base-debian:bullseye
  armhf: ghcr.io/home-assistant/armhf-base-debian:bullseye
  armv7: ghcr.io/home-assistant/armv7-base-debian:bullseye
  i386: ghcr.io/home-assistant/i386-base-debian:bullseye
codenotary:
  signer: me@dje.li
  base_image: notary@home-assistant.io
args:
  FLICD_VERSION: "2.0.3"
