image: "djelibeybi/hassio-flic-{arch}"
shadow_repository: "ghcr.io/djelibeybi"
build_from:
  aarch64: ghcr.io/home-assistant/aarch64-base:3.16
  amd64: ghcr.io/home-assistant/amd64-base:3.16
  armhf: ghcr.io/home-assistant/armhf-base:3.16
  armv7: ghcr.io/home-assistant/armv7-base:3.16
  i386: ghcr.io/home-assistant/i386-base:3.16
codenotary:
  signer: me@dje.li
  base_image: notary@home-assistant.io
args:
  FLICD_VERSION: "2.0.3"
