---
version: 2.0.3
hassio_api: false
slug: flicd
name: flicd
description: Flic daemon
codenotary: me@dje.li
image: djelibeybi/hassio-flicd-{arch}
url: https://github.com/Djelibeybi/hassio-addons/tree/main/flicd
arch:
  - armhf
  - aarch64
  - amd64
  - i386
init: false
options:
  hci_dev: hci0
ports:
  5551/tcp: 5551
ports_description:
  5551/tcp: Inbound port for flic component connection
host_network: true
devices:
  - /dev/hci*
privileged:
  - NET_ADMIN
schema:
  hci_dev: str
